"""Apache2 configuration generator.

Generates VirtualHost blocks with mod_rewrite rules, mod_proxy, SSL,
IP access control, header validation, and redirect rules.
"""

from __future__ import annotations

from infraguard.backends.base import GeneratorOptions
from infraguard.config.schema import InfraGuardConfig
from infraguard.profiles.models import C2Profile


def generate_apache(
    config: InfraGuardConfig,
    profiles: dict[str, C2Profile],
    options: GeneratorOptions,
) -> str:
    lines = [
        "# Apache2 Configuration generated by InfraGuard",
        "# Transform chain validation and scoring pipeline require the InfraGuard proxy.",
        "",
    ]

    for domain_name, domain_config in config.domains.items():
        profile = profiles.get(domain_name)
        if not profile:
            continue

        redirect_target = options.redirect_url or domain_config.drop_action.target
        aliases = options.server_name_aliases.get(domain_name, [])

        # ── VirtualHost block ─────────────────────────────────────────
        lines.append(f"<VirtualHost {options.listen_host}:{options.listen_port}>")
        lines.append(f"    ServerName {domain_name}")
        if aliases:
            lines.append(f"    ServerAlias {' '.join(aliases)}")
        lines.append("")

        # SSL
        cert = options.ssl_cert
        key = options.ssl_key
        if not cert and config.listeners:
            for lis in config.listeners:
                if lis.tls and domain_name in lis.domains:
                    cert = str(lis.tls.cert)
                    key = str(lis.tls.key)
                    break
        if cert and key:
            lines.extend([
                "    SSLEngine On",
                f"    SSLCertificateFile    {cert}",
                f"    SSLCertificateKeyFile {key}",
                "",
            ])

        # SSL proxy settings
        lines.extend([
            "    SSLProxyEngine On",
            "    SSLProxyVerify none",
            "    SSLProxyCheckPeerCN off",
            "    SSLProxyCheckPeerName off",
            "    SSLProxyCheckPeerExpire off",
            "",
        ])

        # Custom response headers
        if options.custom_headers:
            lines.append("    # Custom response headers")
            for h_name, h_value in options.custom_headers.items():
                lines.append(f'    Header set {h_name} "{_esc(h_value)}"')
            lines.append("")

        # IP access control
        if options.include_ip_filtering and domain_config.whitelist_cidrs:
            lines.append("    # IP whitelist")
            lines.append("    <Location />")
            lines.append("        Require all denied")
            for cidr in domain_config.whitelist_cidrs:
                lines.append(f"        Require ip {cidr}")
            lines.append("    </Location>")
            lines.append("")

        # Rewrite engine
        lines.extend([
            "    RewriteEngine On",
            "",
        ])

        # ── Content delivery routes ───────────────────────────────────
        if domain_config.content_routes:
            lines.append("    # Content delivery routes")
            for cr in domain_config.content_routes:
                pat = cr.path
                if pat.endswith("/*"):
                    regex = f"^{_esc_re(pat[:-2])}/"
                else:
                    regex = f"^{_esc_re(pat)}$"
                if cr.backend.type.value in ("pwndrop", "http_proxy"):
                    lines.append(f'    RewriteCond %{{REQUEST_URI}} "{regex}"')
                    lines.append(f"    RewriteRule ^(.*)$ {cr.backend.target}$1 [P,L]")
                elif cr.backend.type.value == "filesystem":
                    lines.append(f"    Alias {pat.rstrip('/*')} {cr.backend.target}")
                lines.append("")

        # ── C2 URI rules ──────────────────────────────────────────────
        all_uris = profile.all_uris()
        if all_uris:
            uri_pattern = "|".join(f"^{_esc_re(u)}$" for u in all_uris)

            # User-Agent condition
            if profile.useragent:
                lines.extend([
                    "    # Validate User-Agent",
                    f'    RewriteCond %{{HTTP_USER_AGENT}} "^{_esc_re(profile.useragent)}$"',
                ])

            # Header conditions
            if options.include_header_checks:
                seen: set[str] = set()
                for verb in ("GET", "POST"):
                    for hdr, val in profile.expected_headers(verb).items():
                        if hdr.lower() in ("host",) or hdr in seen:
                            continue
                        seen.add(hdr)
                        lines.append(
                            f'    RewriteCond %{{HTTP:{hdr}}} "^{_esc_re(val)}$"'
                        )

            # URI match + proxy
            lines.extend([
                "    # Match C2 URIs and proxy to upstream",
                f'    RewriteCond %{{REQUEST_URI}} "{uri_pattern}"',
                f"    RewriteRule ^(.*)$ {domain_config.upstream}$1 [P,L]",
                "",
            ])

        # ── Default action ────────────────────────────────────────────
        lines.append("    # Default: block non-matching requests")
        if options.default_action == "404":
            lines.append("    RewriteRule ^.*$ - [R=404,L]")
        else:
            lines.append(f"    RewriteRule ^.*$ {redirect_target} [R=302,L]")
        lines.extend(["", "</VirtualHost>", ""])

    return "\n".join(lines)


def _esc(s: str) -> str:
    return s.replace('"', '\\"')


def _esc_re(text: str) -> str:
    """Escape special regex characters for Apache RewriteCond."""
    special = r"\.^$*+?()[]{}|"
    for ch in special:
        text = text.replace(ch, "\\" + ch)
    return text
