"""Caddy configuration generator.

Generates a Caddyfile with route matching, header validation, IP
filtering, TLS configuration, and reverse proxy to the upstream C2.
"""

from __future__ import annotations

from infraguard.backends.base import GeneratorOptions
from infraguard.config.schema import InfraGuardConfig
from infraguard.profiles.models import C2Profile


def generate_caddy(
    config: InfraGuardConfig,
    profiles: dict[str, C2Profile],
    options: GeneratorOptions,
) -> str:
    lines = [
        "# Caddyfile generated by InfraGuard",
        "# Transform chain validation and scoring pipeline require the InfraGuard proxy.",
        "",
    ]

    for domain_name, domain_config in config.domains.items():
        profile = profiles.get(domain_name)
        if not profile:
            continue

        redirect_target = options.redirect_url or domain_config.drop_action.target
        aliases = options.server_name_aliases.get(domain_name, [])
        site_addresses = ", ".join([domain_name, *aliases])

        # ── site block ────────────────────────────────────────────────
        lines.append(f"{site_addresses} {{")

        # TLS
        cert = options.ssl_cert
        key = options.ssl_key
        if not cert and config.listeners:
            for lis in config.listeners:
                if lis.tls and domain_name in lis.domains:
                    cert = str(lis.tls.cert)
                    key = str(lis.tls.key)
                    break
        if cert and key:
            lines.extend([
                "    tls {",
                f"        load {cert} {key}",
                "    }",
                "",
            ])

        # Custom response headers
        if options.custom_headers:
            lines.append("    # Custom response headers")
            lines.append("    header {")
            for h_name, h_value in options.custom_headers.items():
                lines.append(f'        {h_name} "{h_value}"')
            lines.append("    }")
            lines.append("")

        # ── C2 URI routes ─────────────────────────────────────────────
        all_uris = profile.all_uris()
        for uri in all_uris:
            lines.append(f"    route {uri} {{")

            # Build matcher conditions
            matcher_parts: list[str] = []

            # IP filtering
            if options.include_ip_filtering and domain_config.whitelist_cidrs:
                cidrs = " ".join(domain_config.whitelist_cidrs)
                matcher_parts.append(f"        @allowed remote_ip {cidrs}")

            # User-Agent + header matching
            if profile.useragent:
                matcher_parts.append(
                    f'        @c2agent header User-Agent "{profile.useragent}"'
                )

            if options.include_header_checks:
                # Collect expected headers for compound matching
                seen: set[str] = set()
                header_conditions: list[str] = []
                for verb in ("GET", "POST"):
                    for hdr, val in profile.expected_headers(verb).items():
                        if hdr.lower() in ("host",) or hdr in seen:
                            continue
                        seen.add(hdr)
                        header_conditions.append(f'header {hdr} "{val}"')
                if header_conditions:
                    all_conds = " ".join(header_conditions)
                    matcher_parts.append(f"        @c2headers {all_conds}")

            for part in matcher_parts:
                lines.append(part)

            # Determine the most restrictive matcher name
            if domain_config.whitelist_cidrs and options.include_ip_filtering:
                matcher = "@allowed"
            elif profile.useragent:
                matcher = "@c2agent"
            elif options.include_header_checks and any(
                profile.expected_headers(v) for v in ("GET", "POST")
            ):
                matcher = "@c2headers"
            else:
                matcher = ""

            if matcher:
                lines.extend([
                    f"        reverse_proxy {matcher} {{",
                    f"            to {domain_config.upstream}",
                    "            transport http {",
                    "                tls_insecure_skip_verify",
                    "            }",
                    "        }",
                    "",
                    f"        redir {redirect_target}",
                ])
            else:
                lines.extend([
                    "        reverse_proxy {",
                    f"            to {domain_config.upstream}",
                    "            transport http {",
                    "                tls_insecure_skip_verify",
                    "            }",
                    "        }",
                ])

            lines.extend(["    }", ""])

        # ── Default action ────────────────────────────────────────────
        lines.append("    # Default: block non-matching requests")
        lines.append("    route {")
        if options.default_action == "404":
            lines.append("        respond 404")
        else:
            lines.append(f"        redir {redirect_target}")
        lines.extend(["    }", "}", ""])

    return "\n".join(lines)
