"""Nginx configuration generator.

Generates nginx server blocks with URI matching, User-Agent validation,
header checks, IP allow/deny, TLS, and proxy_pass to the upstream C2.
"""

from __future__ import annotations

from infraguard.backends.base import GeneratorOptions
from infraguard.config.schema import DomainConfig, InfraGuardConfig
from infraguard.profiles.models import C2Profile


def generate_nginx(
    config: InfraGuardConfig,
    profiles: dict[str, C2Profile],
    options: GeneratorOptions,
) -> str:
    lines = [
        "# Nginx Configuration generated by InfraGuard",
        "# Transform chain validation and scoring pipeline require the InfraGuard proxy.",
        "",
    ]

    for domain_name, domain_config in config.domains.items():
        profile = profiles.get(domain_name)
        if not profile:
            continue

        redirect_target = options.redirect_url or domain_config.drop_action.target
        aliases = options.server_name_aliases.get(domain_name, [])
        server_names = " ".join([domain_name, *aliases])

        # ── server block ──────────────────────────────────────────────
        lines.append(f"server {{")
        lines.append(f"    server_name {server_names};")
        lines.append(f"    listen {options.listen_host}:{options.listen_port} ssl;")
        lines.append("")

        # TLS
        cert = options.ssl_cert
        key = options.ssl_key
        if not cert and config.listeners:
            for lis in config.listeners:
                if lis.tls and domain_name in lis.domains:
                    cert = str(lis.tls.cert)
                    key = str(lis.tls.key)
                    break
        if cert and key:
            lines.extend([
                f"    ssl_certificate     {cert};",
                f"    ssl_certificate_key {key};",
                f"    ssl_protocols       TLSv1.2 TLSv1.3;",
                "",
            ])

        # Custom response headers
        if options.custom_headers:
            lines.append("    # Custom response headers")
            for h_name, h_value in options.custom_headers.items():
                lines.append(f'    add_header {h_name} "{_esc(h_value)}" always;')
            lines.append("")

        # IP filtering
        if options.include_ip_filtering and domain_config.whitelist_cidrs:
            lines.append("    # IP whitelist (only these CIDRs are allowed)")
            for cidr in domain_config.whitelist_cidrs:
                lines.append(f"    allow {cidr};")
            lines.append("    deny all;")
            lines.append("")

        # User-Agent validation
        if profile.useragent:
            lines.extend([
                "    # User-Agent validation",
                "    set $c2_ua_match 0;",
                f'    if ($http_user_agent = "{_esc(profile.useragent)}") {{',
                "        set $c2_ua_match 1;",
                "    }",
                "",
            ])

        # ── Content delivery routes ───────────────────────────────────
        if domain_config.content_routes:
            lines.append("    # Content delivery routes (evaluated before C2 URIs)")
            for cr in domain_config.content_routes:
                pat = cr.path
                if pat.endswith("/*"):
                    loc = f"location {pat[:-1]} {{"  # /downloads/* → /downloads/
                else:
                    loc = f"location = {pat} {{"
                lines.append(f"    {loc}")
                if cr.backend.type.value in ("pwndrop", "http_proxy"):
                    lines.append(f"        proxy_pass {cr.backend.target};")
                    lines.append("        proxy_set_header Host $host;")
                    lines.append("        proxy_ssl_verify off;")
                elif cr.backend.type.value == "filesystem":
                    lines.append(f"        alias {cr.backend.target};")
                lines.append("    }")
                lines.append("")

        # ── C2 URI locations ──────────────────────────────────────────
        all_uris = profile.all_uris()
        if all_uris:
            lines.append("    # C2 URI endpoints")
            for uri in all_uris:
                lines.append(f"    location = {uri} {{")

                # UA check
                if profile.useragent:
                    lines.extend([
                        "        if ($c2_ua_match = 0) {",
                        f"            return 302 {redirect_target};",
                        "        }",
                    ])

                # Header validation (merge GET + POST expected headers)
                if options.include_header_checks:
                    seen: set[str] = set()
                    for verb in ("GET", "POST"):
                        for hdr, val in profile.expected_headers(verb).items():
                            if hdr.lower() in ("host",) or hdr in seen:
                                continue
                            seen.add(hdr)
                            var = "$http_" + hdr.lower().replace("-", "_")
                            lines.extend([
                                f'        if ({var} != "{_esc(val)}") {{',
                                f"            return 302 {redirect_target};",
                                "        }",
                            ])

                lines.extend([
                    f"        proxy_pass {domain_config.upstream};",
                    "        proxy_set_header Host $host;",
                    "        proxy_set_header X-Real-IP $remote_addr;",
                    "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                    "        proxy_set_header X-Forwarded-Proto $scheme;",
                    "        proxy_ssl_verify off;",
                    "    }",
                    "",
                ])

        # ── Default action ────────────────────────────────────────────
        lines.append("    # Default: block non-matching requests")
        lines.append("    location / {")
        if options.default_action == "404":
            lines.append("        return 404;")
        else:
            lines.append(f"        return 302 {redirect_target};")
        lines.extend(["    }", "}", ""])

    return "\n".join(lines)


def _esc(s: str) -> str:
    return s.replace('"', '\\"')
