apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infraguard.fullname" . }}-config
  labels: {{- include "infraguard.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ tpl .Values.config.contents . | indent 4 }}
